/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical.pkgcase.management;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Vishant
 */
public class SaveImages extends javax.swing.JFrame {

    /**
     * Creates new form SaveImages
     */
    public SaveImages(String pat_id, String visit_id) {
        initComponents();
        //String visitID = "";
        patientID = pat_id;
        visitID = visit_id;
        patientID=patientID.replaceAll(":", "");
        patientID=patientID.replaceAll("-", "");
        visitID=visitID.replaceAll(":", "");
        visitID=visitID.replaceAll("-", "");


        System.out.println("print:  "+patientID +" "+ visitID);
        fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter jpgfilter = new FileNameExtensionFilter("JPEG Files", "jpg");
        FileNameExtensionFilter pngfilter = new FileNameExtensionFilter("PNG Files", "png");
               


        fileChooser.addChoosableFileFilter(jpgfilter);
                fileChooser.addChoosableFileFilter(pngfilter);

                setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        // TODO add your handling code here:
         if (evt.getActionCommand().equals(javax.swing.JFileChooser.APPROVE_SELECTION)) {
        File theDir = new File("Diagnosis Storage Folder/"+File.separator+patientID+File.separator+visitID);
        //File visitDir = new File(theDir + "/" + visitID);// Defining Directory/Folder Name  
    try{   
        if (!theDir.exists()){  // Checks that Directory/Folder Doesn't Exists!  
         boolean result = theDir.mkdirs();    
        }  
    }catch(Exception e){  
        JOptionPane.showMessageDialog(null, e);  
    }  
         counter++;        
       
         
         
         JOptionPane.showMessageDialog(null, "File number " + counter + " saved");
         String path = fileChooser.getSelectedFile().getAbsolutePath();
         System.out.println(fileChooser.getSelectedFile().getName());
         String extension[] = fileChooser.getSelectedFile().getName().split("\\.");
         int last = extension.length;
                  String finalExtension = extension[last-1];

         
         
         JOptionPane.showMessageDialog(null, path);
         
         File src = new File(path);
        File target = new File(theDir.getAbsolutePath()+File.separator+counter+"."+finalExtension);

        try
        {
        Files.copy(src.toPath(), target.toPath(), StandardCopyOption.REPLACE_EXISTING);
        }
        catch(Exception e)
        {}
        finally{
            this.dispose();
        MainWindow mw = new MainWindow();
        }
                 

        
    } else if (evt.getActionCommand().equals(javax.swing.JFileChooser.CANCEL_SELECTION)) {
            this.dispose();
        MainWindow mw = new MainWindow();
        
        
    }
    
        
        
    }//GEN-LAST:event_fileChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveImages.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SaveImages().setVisible(true);
            }
        });
    }

    public int counter = 0;
    String patientID = new String();
    String visitID = new String();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    // End of variables declaration//GEN-END:variables
}
