/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical.pkgcase.management;

/**
 *
 * @author pranali
 */
public class VisitDialog extends javax.swing.JDialog {

    /**
     * Creates new form VisitDialog
     */
    
    String pat_id = new String();
    public VisitDialog(java.awt.Frame parent, boolean modal, String pat_id) {
        super(parent, modal);
        
        this.pat_id = pat_id;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane31 = new javax.swing.JScrollPane();
        jPanel13 = new javax.swing.JPanel();
        chiefComplaintLabel = new javax.swing.JLabel();
        jScrollPane32 = new javax.swing.JScrollPane();
        chiefComplaintInput = new javax.swing.JTextArea();
        habitLabel = new javax.swing.JLabel();
        jScrollPane36 = new javax.swing.JScrollPane();
        habitInput = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        appetiteLabel = new javax.swing.JLabel();
        thirstLabel = new javax.swing.JLabel();
        likeLabel = new javax.swing.JLabel();
        aversionLabel = new javax.swing.JLabel();
        stoolLabel = new javax.swing.JLabel();
        urineLabel = new javax.swing.JLabel();
        perspirationLabel = new javax.swing.JLabel();
        sleepLabel = new javax.swing.JLabel();
        dreamsLabel = new javax.swing.JLabel();
        thermallyLabel = new javax.swing.JLabel();
        gynacHistoryLabel1 = new javax.swing.JLabel();
        mindLabel1 = new javax.swing.JLabel();
        jScrollPane27 = new javax.swing.JScrollPane();
        thermalInput = new javax.swing.JTextArea();
        jScrollPane28 = new javax.swing.JScrollPane();
        gynacHistoryInput = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        mindInput = new javax.swing.JTextArea();
        likeComboBox = new javax.swing.JComboBox<>();
        urineComboBox = new javax.swing.JComboBox<>();
        extraLikesInput = new javax.swing.JTextField();
        extraUrineInput = new javax.swing.JTextField();
        appetiteComboBox = new javax.swing.JComboBox<>();
        thirstComboBox = new javax.swing.JComboBox<>();
        stoolComboBox = new javax.swing.JComboBox<>();
        aversionComboBox = new javax.swing.JComboBox<>();
        extraAppetiteInput = new javax.swing.JTextField();
        extraThirstInput = new javax.swing.JTextField();
        extraAversionInput = new javax.swing.JTextField();
        extraStoolInput = new javax.swing.JTextField();
        sleepComboBox = new javax.swing.JComboBox<>();
        dreamsComboBox = new javax.swing.JComboBox<>();
        perspirationComboBox = new javax.swing.JComboBox<>();
        extraPerspirationInput = new javax.swing.JTextField();
        sleepInput = new javax.swing.JTextField();
        extraDreamsInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pePanel = new javax.swing.JPanel();
        generalTitleLabel = new javax.swing.JLabel();
        temperatureLabel = new javax.swing.JLabel();
        pulseInput = new javax.swing.JTextField();
        pulseLabel = new javax.swing.JLabel();
        temperatureInput = new javax.swing.JTextField();
        respiratoryRateInput = new javax.swing.JTextField();
        respiratoryRateLabel = new javax.swing.JLabel();
        othersInput = new javax.swing.JScrollPane();
        otherInput = new javax.swing.JTextArea();
        othersLabel = new javax.swing.JLabel();
        vitalTitleLabel = new javax.swing.JLabel();
        cvsLabel = new javax.swing.JLabel();
        cvsInput = new javax.swing.JTextField();
        rsLabel = new javax.swing.JLabel();
        rsInput = new javax.swing.JTextField();
        cnsLabel = new javax.swing.JLabel();
        cnsInput = new javax.swing.JTextField();
        paLabel = new javax.swing.JLabel();
        paInput = new javax.swing.JScrollPane();
        invgInput = new javax.swing.JTextArea();
        invgLabel = new javax.swing.JLabel();
        PAInput = new javax.swing.JTextField();
        miasmLabel = new javax.swing.JLabel();
        miasmInput = new javax.swing.JTextField();
        bpLabel = new javax.swing.JLabel();
        bpInput = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        diagPanel = new javax.swing.JPanel();
        finalDiagnosisLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        finalDiagnosisInput = new javax.swing.JTextArea();
        probableRemediesLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        probableRemediesInput = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(208, 43));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(211, 50));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Visits"));

        chiefComplaintLabel.setText("Chief Complaint");

        chiefComplaintInput.setColumns(20);
        chiefComplaintInput.setLineWrap(true);
        chiefComplaintInput.setRows(5);
        jScrollPane32.setViewportView(chiefComplaintInput);

        habitLabel.setText("Habit/Addiction");

        habitInput.setColumns(20);
        habitInput.setLineWrap(true);
        habitInput.setRows(5);
        jScrollPane36.setViewportView(habitInput);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(habitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane36, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(chiefComplaintLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane32, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chiefComplaintLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(habitLabel))
                .addContainerGap(542, Short.MAX_VALUE))
        );

        jScrollPane31.setViewportView(jPanel13);

        jTabbedPane1.addTab("Visit Details", jScrollPane31);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Physical Generals"));

        appetiteLabel.setText("Appetite");

        thirstLabel.setText("Thirst");

        likeLabel.setText("Likes");

        aversionLabel.setText("Aversion");

        stoolLabel.setText("Stool");

        urineLabel.setText("Urine");

        perspirationLabel.setText("Perspiration");

        sleepLabel.setText("Sleep");

        dreamsLabel.setText("Dreams");

        thermallyLabel.setText("Thermally");

        gynacHistoryLabel1.setText("Gynac History");

        mindLabel1.setText("Mind");

        thermalInput.setColumns(20);
        thermalInput.setLineWrap(true);
        thermalInput.setRows(5);
        jScrollPane27.setViewportView(thermalInput);

        gynacHistoryInput.setColumns(20);
        gynacHistoryInput.setLineWrap(true);
        gynacHistoryInput.setRows(5);
        jScrollPane28.setViewportView(gynacHistoryInput);

        mindInput.setColumns(20);
        mindInput.setLineWrap(true);
        mindInput.setRows(5);
        jScrollPane29.setViewportView(mindInput);

        likeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NA", "Sweet", "Salty", "Sour", "Bitter", "Spicy" }));

        urineComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Normal", "Low" }));
        urineComboBox.setSelectedIndex(1);

        extraUrineInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extraUrineInputActionPerformed(evt);
            }
        });

        appetiteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Normal", "Low", "" }));
        appetiteComboBox.setSelectedIndex(1);

        thirstComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Normal", "Low" }));
        thirstComboBox.setSelectedIndex(1);

        stoolComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Normal", "Low" }));
        stoolComboBox.setSelectedIndex(1);

        aversionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NA", "Sweet", "Spicy", "Sour", "Bitter", "Salty" }));

        sleepComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Normal", "Low" }));
        sleepComboBox.setSelectedIndex(1);
        sleepComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sleepComboBoxActionPerformed(evt);
            }
        });

        dreamsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        perspirationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "High", "Normal", "Low" }));
        perspirationComboBox.setSelectedIndex(1);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appetiteLabel)
                    .addComponent(thirstLabel)
                    .addComponent(likeLabel)
                    .addComponent(aversionLabel)
                    .addComponent(stoolLabel)
                    .addComponent(urineLabel)
                    .addComponent(mindLabel1)
                    .addComponent(gynacHistoryLabel1)
                    .addComponent(thermallyLabel)
                    .addComponent(dreamsLabel)
                    .addComponent(sleepLabel)
                    .addComponent(perspirationLabel))
                .addGap(26, 26, 26)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane27, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                    .addComponent(jScrollPane28)
                    .addComponent(jScrollPane29)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(aversionComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(thirstComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(appetiteComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(likeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 131, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(extraLikesInput, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(extraAppetiteInput)
                                    .addComponent(extraThirstInput)
                                    .addComponent(extraAversionInput)))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(stoolComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(urineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sleepComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(perspirationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(extraUrineInput, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                    .addComponent(extraStoolInput)
                                    .addComponent(extraPerspirationInput)
                                    .addComponent(sleepInput)))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(dreamsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(extraDreamsInput)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appetiteLabel)
                    .addComponent(appetiteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extraAppetiteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(thirstLabel)
                            .addComponent(thirstComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraThirstInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(likeLabel)
                            .addComponent(likeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraLikesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aversionLabel)
                            .addComponent(aversionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraAversionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stoolLabel)
                            .addComponent(stoolComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraStoolInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(urineLabel)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraUrineInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)))
                .addGap(3, 3, 3)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(perspirationLabel)
                            .addComponent(perspirationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraPerspirationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(sleepLabel))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sleepComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sleepInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(dreamsLabel)
                        .addGap(26, 26, 26)
                        .addComponent(thermallyLabel))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dreamsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraDreamsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(gynacHistoryLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(mindLabel1))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jScrollPane18.setViewportView(jPanel12);

        jTabbedPane1.addTab("Physical Details", jScrollPane18);

        pePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Physical Examination"));

        generalTitleLabel.setText("General -");

        temperatureLabel.setText("Temperature");

        pulseInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulseInputActionPerformed(evt);
            }
        });

        pulseLabel.setText("Pulse");

        temperatureInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureInputActionPerformed(evt);
            }
        });

        respiratoryRateLabel.setText("Respiratory Rate");

        otherInput.setColumns(20);
        otherInput.setLineWrap(true);
        otherInput.setRows(5);
        othersInput.setViewportView(otherInput);

        othersLabel.setText("Others");

        vitalTitleLabel.setText("Systemic with vital data - ");

        cvsLabel.setText("CVS");

        cvsInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvsInputActionPerformed(evt);
            }
        });

        rsLabel.setText("RS");

        cnsLabel.setText("CNS");

        paLabel.setText("P/A");

        invgInput.setColumns(20);
        invgInput.setLineWrap(true);
        invgInput.setRows(5);
        paInput.setViewportView(invgInput);

        invgLabel.setText("INVG Assigned");

        miasmLabel.setText("Miasm");

        bpLabel.setText("Blood Pressure");

        bpInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pePanelLayout = new javax.swing.GroupLayout(pePanel);
        pePanel.setLayout(pePanelLayout);
        pePanelLayout.setHorizontalGroup(
            pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pePanelLayout.createSequentialGroup()
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(generalTitleLabel))
                    .addGroup(pePanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pePanelLayout.createSequentialGroup()
                                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(temperatureLabel)
                                    .addComponent(pulseLabel))
                                .addGap(40, 40, 40)
                                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pulseInput, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(temperatureInput)))
                            .addGroup(pePanelLayout.createSequentialGroup()
                                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(respiratoryRateLabel)
                                    .addComponent(othersLabel)
                                    .addComponent(bpLabel))
                                .addGap(20, 20, 20)
                                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(respiratoryRateInput)
                                    .addGroup(pePanelLayout.createSequentialGroup()
                                        .addComponent(othersInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(bpInput)))))
                    .addGroup(pePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vitalTitleLabel)
                            .addGroup(pePanelLayout.createSequentialGroup()
                                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pePanelLayout.createSequentialGroup()
                                        .addGap(107, 107, 107)
                                        .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rsLabel)
                                            .addComponent(cvsLabel)
                                            .addComponent(cnsLabel)
                                            .addComponent(paLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(miasmLabel))
                                        .addGap(36, 36, 36))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pePanelLayout.createSequentialGroup()
                                        .addComponent(invgLabel)
                                        .addGap(18, 18, 18)))
                                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(rsInput, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cvsInput, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cnsInput, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(paInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(miasmInput, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PAInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(222, 222, 222))
        );
        pePanelLayout.setVerticalGroup(
            pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(generalTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temperatureLabel)
                    .addComponent(temperatureInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pulseInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pulseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bpLabel)
                    .addComponent(bpInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(respiratoryRateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respiratoryRateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(othersInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(othersLabel))
                .addGap(18, 18, 18)
                .addComponent(vitalTitleLabel)
                .addGap(26, 26, 26)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvsLabel)
                    .addComponent(cvsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rsLabel)
                    .addComponent(rsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cnsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnsLabel))
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pePanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(paInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pePanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(invgLabel)))
                .addGap(7, 7, 7)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PAInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miasmInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miasmLabel))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pePanel);

        jTabbedPane1.addTab("Physical Examination", jScrollPane1);

        diagPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Diagnosis/Remedies"));

        finalDiagnosisLabel.setText("Final Diagnosis");

        finalDiagnosisInput.setColumns(20);
        finalDiagnosisInput.setLineWrap(true);
        finalDiagnosisInput.setRows(5);
        jScrollPane.setViewportView(finalDiagnosisInput);

        probableRemediesLabel.setText("Final Remedies");

        probableRemediesInput.setColumns(20);
        probableRemediesInput.setLineWrap(true);
        probableRemediesInput.setRows(5);
        jScrollPane3.setViewportView(probableRemediesInput);

        javax.swing.GroupLayout diagPanelLayout = new javax.swing.GroupLayout(diagPanel);
        diagPanel.setLayout(diagPanelLayout);
        diagPanelLayout.setHorizontalGroup(
            diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(finalDiagnosisLabel)
                    .addComponent(probableRemediesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        diagPanelLayout.setVerticalGroup(
            diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalDiagnosisLabel))
                .addGap(9, 9, 9)
                .addGroup(diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(probableRemediesLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(611, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(diagPanel);

        jTabbedPane1.addTab("Diagnosis/Remedies", jScrollPane2);

        saveButton.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void extraUrineInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extraUrineInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extraUrineInputActionPerformed

    private void sleepComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sleepComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sleepComboBoxActionPerformed

    private void pulseInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulseInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pulseInputActionPerformed

    private void temperatureInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperatureInputActionPerformed

    private void cvsInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvsInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvsInputActionPerformed

    private void bpInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpInputActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Patient id " +pat_id);
        InsertVisitDetail visitdets = new InsertVisitDetail(pat_id,chiefComplaintInput.getText(),habitInput.getText(),appetiteComboBox.getSelectedItem().toString() +" " +extraAppetiteInput.getText(),thirstComboBox.getSelectedItem().toString() + " " + extraThirstInput.getText(),likeComboBox.getSelectedItem().toString() + " "+ extraLikesInput.getText() ,aversionComboBox.getSelectedItem().toString() +" " +extraAversionInput.getText(),stoolComboBox.getSelectedItem().toString() + " " +extraStoolInput.getText(),urineComboBox.getSelectedItem().toString() + " " + extraUrineInput.getText(),perspirationComboBox.getSelectedItem().toString()+" " + extraPerspirationInput.getText(),sleepComboBox.getSelectedItem().toString() + " " +sleepInput.getText(), dreamsComboBox.getSelectedItem().toString() + " " + extraDreamsInput.getText(),thermalInput.getText(),gynacHistoryInput.getText(),mindInput.getText(),temperatureInput.getText(),pulseInput.getText(),bpInput.getText(),respiratoryRateInput.getText(),otherInput.getText(),cvsInput.getText(),rsInput.getText(),cnsInput.getText(),PAInput.getText(), invgInput.getText(),miasmInput.getText(),finalDiagnosisInput.getText(),probableRemediesInput.getText());
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisitDialog dialog = new VisitDialog(new javax.swing.JFrame(), true,"hello");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PAInput;
    private javax.swing.JComboBox<String> appetiteComboBox;
    private javax.swing.JLabel appetiteLabel;
    private javax.swing.JComboBox<String> aversionComboBox;
    private javax.swing.JLabel aversionLabel;
    private javax.swing.JTextField bpInput;
    private javax.swing.JLabel bpLabel;
    private javax.swing.JTextArea chiefComplaintInput;
    private javax.swing.JLabel chiefComplaintLabel;
    private javax.swing.JTextField cnsInput;
    private javax.swing.JLabel cnsLabel;
    private javax.swing.JTextField cvsInput;
    private javax.swing.JLabel cvsLabel;
    private javax.swing.JPanel diagPanel;
    private javax.swing.JComboBox<String> dreamsComboBox;
    private javax.swing.JLabel dreamsLabel;
    private javax.swing.JTextField extraAppetiteInput;
    private javax.swing.JTextField extraAversionInput;
    private javax.swing.JTextField extraDreamsInput;
    private javax.swing.JTextField extraLikesInput;
    private javax.swing.JTextField extraPerspirationInput;
    private javax.swing.JTextField extraStoolInput;
    private javax.swing.JTextField extraThirstInput;
    private javax.swing.JTextField extraUrineInput;
    private javax.swing.JTextArea finalDiagnosisInput;
    private javax.swing.JLabel finalDiagnosisLabel;
    private javax.swing.JLabel generalTitleLabel;
    private javax.swing.JTextArea gynacHistoryInput;
    private javax.swing.JLabel gynacHistoryLabel1;
    private javax.swing.JTextArea habitInput;
    private javax.swing.JLabel habitLabel;
    private javax.swing.JTextArea invgInput;
    private javax.swing.JLabel invgLabel;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> likeComboBox;
    private javax.swing.JLabel likeLabel;
    private javax.swing.JTextField miasmInput;
    private javax.swing.JLabel miasmLabel;
    private javax.swing.JTextArea mindInput;
    private javax.swing.JLabel mindLabel1;
    private javax.swing.JTextArea otherInput;
    private javax.swing.JScrollPane othersInput;
    private javax.swing.JLabel othersLabel;
    private javax.swing.JScrollPane paInput;
    private javax.swing.JLabel paLabel;
    private javax.swing.JPanel pePanel;
    private javax.swing.JComboBox<String> perspirationComboBox;
    private javax.swing.JLabel perspirationLabel;
    private javax.swing.JTextArea probableRemediesInput;
    private javax.swing.JLabel probableRemediesLabel;
    private javax.swing.JTextField pulseInput;
    private javax.swing.JLabel pulseLabel;
    private javax.swing.JTextField respiratoryRateInput;
    private javax.swing.JLabel respiratoryRateLabel;
    private javax.swing.JTextField rsInput;
    private javax.swing.JLabel rsLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> sleepComboBox;
    private javax.swing.JTextField sleepInput;
    private javax.swing.JLabel sleepLabel;
    private javax.swing.JComboBox<String> stoolComboBox;
    private javax.swing.JLabel stoolLabel;
    private javax.swing.JTextField temperatureInput;
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JTextArea thermalInput;
    private javax.swing.JLabel thermallyLabel;
    private javax.swing.JComboBox<String> thirstComboBox;
    private javax.swing.JLabel thirstLabel;
    private javax.swing.JComboBox<String> urineComboBox;
    private javax.swing.JLabel urineLabel;
    private javax.swing.JLabel vitalTitleLabel;
    // End of variables declaration//GEN-END:variables
}
